version = 0.1
[default.pipeline_bootstrap.parameters]
oidc_provider_url = "https://token.actions.githubusercontent.com"
oidc_client_id = "sts.amazonaws.com"
github_org = "javanlth"
github_repo = "aws-pdf-encrypt-sample"
deployment_branch = "main"
oidc_provider = "github-actions"
permissions_provider = "OpenID Connect (OIDC)"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::415725062401:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-yOx5NbCuhjzY"
cloudformation_execution_role = "arn:aws:iam::415725062401:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-qHRF47mqkdS5"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-cjc43zcpnm0f"
image_repository = "415725062401.dkr.ecr.ap-northeast-1.amazonaws.com/aws-sam-cli-managed-dev-pipeline-resources-imagerepository-ss6s8rsogv8i"
region = "ap-northeast-1"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::415725062401:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-JyvXzspQph1x"
cloudformation_execution_role = "arn:aws:iam::415725062401:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-og7fUQNzejvg"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-p1z7s7cemtin"
image_repository = "415725062401.dkr.ecr.ap-northeast-1.amazonaws.com/aws-sam-cli-managed-prod-pipeline-resources-imagerepository-0unnmtrrbzqw"
region = "ap-northeast-1"
