name: Development Stage

on:
  workflow_run:
    workflows: [Unit Test]
    types: [completed]

env:
  SAM_TEMPLATE: template.yaml
  TESTING_STACK_NAME: pdf-encrypt-dev
  TESTING_REGION: ap-northeast-1
  PROD_STACK_NAME: pdf-encrypt-prod
  PROD_REGION: ap-northeast-1
  TEST_PDF: test.pdf

permissions:
  id-token: write
  contents: read
jobs:

  build-and-package-for-dev:
    #if: github.ref == 'refs/heads/main'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Build resources for dev

        run: sam build --template ${SAM_TEMPLATE} --use-container

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ env.TESTING_REGION }}
          role-to-assume: ${{ secrets.TESTING_PIPELINE_EXECUTION_ROLE }}
          role-session-name: testing-packaging
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Upload artifacts to testing artifact buckets
        run: |
          sam package \
            --s3-bucket ${{ secrets.TESTING_ARTIFACTS_BUCKET }} \
            --image-repository ${{ secrets.TESTING_IMAGE_REPOSITORY }} \
            --region ${TESTING_REGION} \
            --output-template-file packaged-testing.yaml

      - uses: actions/upload-artifact@v3
        with:
          name: packaged-testing.yaml
          path: packaged-testing.yaml


  deploy-testing:
    #if: github.ref == 'refs/heads/main'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    needs: [build-and-package-for-dev]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - uses: actions/download-artifact@v3
        with:
          name: packaged-testing.yaml

      - name: Assume the testing pipeline user role
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ env.TESTING_REGION }}
          role-to-assume: ${{ secrets.TESTING_PIPELINE_EXECUTION_ROLE }}
          role-session-name: testing-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Deploy to testing account
        run: |
          sam deploy --stack-name ${TESTING_STACK_NAME} \
            --template packaged-testing.yaml \
            --capabilities CAPABILITY_IAM \
            --region ${TESTING_REGION} \
            --s3-bucket ${{ secrets.TESTING_ARTIFACTS_BUCKET }} \
            --image-repository ${{ secrets.TESTING_IMAGE_REPOSITORY }} \
            --no-fail-on-empty-changeset \
            --role-arn ${{ secrets.TESTING_CLOUDFORMATION_EXECUTION_ROLE }}

  test-lambda-deployment:
    env:
      TESTING_PIPELINE_EXECUTION_ROLE: ${{ secrets.TESTING_PIPELINE_EXECUTION_ROLE }}
    needs: [deploy-testing]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1

      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ env.TESTING_REGION }}
          role-to-assume: ${{ secrets.TESTING_PIPELINE_EXECUTION_ROLE }}
          role-session-name: testing-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Test lambda function
        env:
          DEFAULT_ACCESS_KEY: "${{ secrets.DEFAULT_ACCESS_KEY }}"
          DEFAULT_SECRET_KEY: "${{ secrets.DEFAULT_SECRET_KEY }}"
        run: |
          echo $AWS_SECRET_ACCESS_KEY
          echo $AWS_ACCESS_KEY_ID
          CA_BUNDLE=$(python3 -m certifi)
          aws configure set aws_profile dev
          aws configure set aws_access_key_id $DEFAULT_ACCESS_KEY --profile dev
          aws configure set aws_secret_access_key $DEFAULT_SECRET_KEY --profile dev
          aws configure set region ap-northeast-1 --profile dev
          aws configure set ca_bundle $CA_BUNDLE --profile dev
 
          aws configure list
          aws s3api put-object --bucket ${TESTING_STACK_NAME}-mocho --key test.pdf --body test.pdf --profile dev
          #cd deploy_test
          #pip install pytest
          #pip install -r requirements.txt
          #pytest -s -v
          #cd ..